name: Release
on:
  push: # { tags: v* }
  workflow_dispatch:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - run: bundle exec rake build
      - run: >
          gem push --key github
          --host https://rubygems.pkg.github.com/${{github.repository_owner}}
          pkg/*.gem
